config/routes.rb
Rails.application.routes.draw do

  resources :tracks do
    resources :records
  end

  resources :mypage, only: [:index] do
    collection do
      get :tweet
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks" 
  }

  root 'top#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :user
  has_many :records
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :omniauthable, :recoverable,
	         :registerable, :rememberable, :trackable, :validatable

  has_many :tracks

	def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:     auth.info.nickname,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    User.create_unique_email,
                         password: Devise.friendly_token[0,20]
                        )
    end
    user
  end
 
  # 通常サインアップ時のuid用、Twitter OAuth認証時のemail用にuuidな文字列を生成
  def self.create_unique_string
    SecureRandom.uuid
  end
 
  # twitterではemailを取得できないので、適当に一意のemailを生成
  def self.create_unique_email
    User.create_unique_string + "@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    mypage_index_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
  	@user = current_user
    @tracks = @user.tracks
  end

  def tweet
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Settings.twitter_key
      config.consumer_secret     = Settings.twitter_secret
      config.access_token        = session[:oauth_token]
      config.access_token_secret = session[:oauth_token_secret]
    end
    client.update("眠くなってきた、、こっから！")
    redirect_to mypage_index_path
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @record }
      else
        format.html { render action: 'new' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:track_id, :start_time, :end_time)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Settings.twitter_key
      config.consumer_secret     = Settings.twitter_secret
      config.access_token        = session[:oauth_token]
      config.access_token_secret = session[:oauth_token_secret]
    end

    start_words = client.search("from:#{current_user.name} #{@track.start_word}")
    end_words = client.search("from:#{current_user.name} #{@track.end_word}")

    latest_record = @track.records.order('start_time DESC').first
    if latest_record
      latest_start_time = latest_record.start_time
    end

    start_words.zip(end_words).each do |start_word, end_word|
      start_time = start_word.created_at
      end_time = end_word.created_at
      
      if !end_time
        break
      end

      if latest_start_time && start_time <= latest_start_time
        break
      end

      @record = @track.records.build(start_time: start_time, end_time: end_time)
      @record.save 
    end

  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = current_user.tracks.build(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render action: 'show', status: :created, location: @track }
      else
        format.html { render action: 'new' }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:start_word, :end_word)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
    auth = request.env["omniauth.auth"]
    session[:oauth_token] = auth['credentials']['token']
    session[:oauth_token_secret] = auth['credentials']['secret']
 
    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a><%= link_to "TimeTrack", root_path%></a>
    by Progate
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to '#', id: "logo" do %>
        <i class="fa fa-twitter"></i>
      <% end %>
      <nav>
        <ul class="nav pull-right">
          <li class="log-out"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTrack</title>
    <!-- <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"> -->
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/mypage/index.html.erb
<div class="mypage_main-contents">
	<ul class="users">
		<li><%= @user.name %></li>
		<li><%= @text %></li>
		<li><%= link_to '新規ワード登録', new_track_path %></li>
		<li><%= link_to 'つぶやく', tweet_mypage_index_path %></li>
	</ul>
</div>

app/views/mypage/index.html.haml
.mypage_main-contents
  %ul.users
    %li= @user.name
    %li= @text
    %li= link_to '新規ワード登録', new_track_path
    %li= link_to 'つぶやく', tweet_mypage_index_path

%section.container
  .col-xs-12.col-sm-6.col-md-6.col-lg-12
    .content-panel
      %h3 登録済みワード一覧

      %table.table.table-striped.table-hover
        %thead
          %tr
            %th 開始
            %th 終了
            %th
            %th
            %th
        %tbody
          = render @tracks

app/views/records/_form.html.haml
= form_for @record do |f|
  - if @record.errors.any?
    #error_explanation
      %h2= "#{pluralize(@record.errors.count, "error")} prohibited this record from being saved:"
      %ul
        - @record.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :track_id
    = f.number_field :track_id
  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .field
    = f.label :end_time
    = f.datetime_select :end_time
  .actions
    = f.submit 'Save'

app/views/records/_record.html.haml
%tr
  %td= record.start_time
  %td= record.end_time
  %td= record.end_time - record.start_time
  / %td= link_to '内容を見る', track
  / %td= link_to '編集する', edit_track_path(track)
  / %td= link_to '削除する', track, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/records/edit.html.haml
%h1 Editing record

= render 'form'

= link_to 'Show', @record
\|
= link_to 'Back', records_path

app/views/records/index.html.haml
%h1 Listing records

%table
  %thead
    %tr
      %th Track
      %th Start time
      %th End time
      %th
      %th
      %th
      
  %tbody
    - @records.each do |record|
      %tr
        %td= record.track_id
        %td= record.start_time
        %td= record.end_time
        %td= link_to 'Show', record
        %td= link_to 'Edit', edit_record_path(record)
        %td= link_to 'Destroy', record, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Record', new_record_path

app/views/records/new.html.haml
%h1 New record

= render 'form'

= link_to 'Back', records_path

app/views/records/show.html.haml
%p#notice= notice

%p
  %b Track:
  = @record.track_id
%p
  %b Start time:
  = @record.start_time
%p
  %b End time:
  = @record.end_time

= link_to 'Edit', edit_record_path(@record)
\|
= link_to 'Back', records_path

app/views/top/index.html.erb
<!-- <div class="title Welcome to Timetrack"</div>
<div class="twitter-login">
	<!-- <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %> -->
 
<!--Navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Progate</a>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to  "Log In", user_omniauth_authorize_path(:twitter) %></li>
      </ul>
    </div> 
  </div>
</nav><!-- End navbar -->

<!-- Jumbotron -->
<div class="jumbotron">
  <div class="container">
  <h1>Time Track</h1>
  <p>Twitterで、簡単に出退勤管理！</p>
  <p>
    <a class="btn btn-primary btn-lg" href="http://twitter.com">新規登録</a>
  	</p>
  	<div class="used-user">
  		<small>既にアカウントをお持ちですか?</small>
  	</div>
  	<div class="used-user">
  		<%=link_to  "Log In", user_omniauth_authorize_path(:twitter) , class: "btn btn-default btn-lg"%>
  	</div>
  </div>
</div><!-- End Jumbotron -->

<!-- Footer -->
<div class="footer">
  <div class="container">
    <div class="row">
    </div>
     <hr>
    <p>&copy; 2014 Progate. Inc</p>
    </div>
  <!-- End Footer -->
</div>

app/views/tracks/_form.html.haml
= form_for @track do |f|
  - if @track.errors.any?
    #error_explanation
      %h2= "#{pluralize(@track.errors.count, "error")} prohibited this track from being saved:"
      %ul
        - @track.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :start_word
    = f.text_field :start_word
  .field
    = f.label :end_word
    = f.text_field :end_word
  .actions
    = f.submit 'Save'

app/views/tracks/_track.html.haml
%tr
  %td= track.start_word
  %td= track.end_word
  %td= link_to '内容を見る', track
  %td= link_to '編集する', edit_track_path(track)
  %td= link_to '削除する', track, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/tracks/edit.html.haml
%h1 Editing track

= render 'form'

= link_to 'Show', @track
\|
= link_to 'Back', tracks_path

app/views/tracks/index.html.haml
%h1 Listing tracks

%table
  %thead
    %tr
      %th User
      %th Start Word
      %th End Word
      %th
      %th
      %th
      
  %tbody
    - @tracks.each do |track|
      %tr
        %td= track.user_id
        %td= track.start_word
        %td= track.end_word
        %td= link_to 'Show', track
        %td= link_to 'Edit', edit_track_path(track)
        %td= link_to 'Destroy', track, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Track', new_track_path

app/views/tracks/new.html.haml
%h1 New track

= render 'form'

= link_to 'Back', tracks_path

app/views/tracks/show.html.haml
%p#notice= notice

= render @track.records

%p
  %b User:
  = @track.user_id
%p
  %b Word:
  = @track.word

= link_to 'Edit', edit_track_path(@track)
\|
= link_to 'Back', tracks_path